/**
 * Yoast.com provisioning API
 * The Yoast provisioning API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CreateProvisionedSubscriptionDto model module.
* @module model/CreateProvisionedSubscriptionDto
* @version 1.0.0
*/
export default class CreateProvisionedSubscriptionDto {
    /**
    * Constructs a new <code>CreateProvisionedSubscriptionDto</code>.
    * @alias module:model/CreateProvisionedSubscriptionDto
    * @class
    * @param customerEmail {String} The email address of the customer.
    * @param productCode {String} The product-code of the product the subscription is for.
    * @param site {String} The site URL that the subscription needs to be connectd to.
    * @param firstName {String} The first name of the customer.
    * @param lastName {String} The last name of the customers.
    */

    constructor(customerEmail, productCode, site, firstName, lastName) {
        
        
        this['customerEmail'] = customerEmail;
        this['productCode'] = productCode;
        this['site'] = site;
        this['firstName'] = firstName;
        this['lastName'] = lastName;
        
    }

    /**
    * Constructs a <code>CreateProvisionedSubscriptionDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CreateProvisionedSubscriptionDto} obj Optional instance to populate.
    * @return {module:model/CreateProvisionedSubscriptionDto} The populated <code>CreateProvisionedSubscriptionDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateProvisionedSubscriptionDto();
                        
            
            if (data.hasOwnProperty('customerEmail')) {
                obj['customerEmail'] = ApiClient.convertToType(data['customerEmail'], 'String');
            }
            if (data.hasOwnProperty('productCode')) {
                obj['productCode'] = ApiClient.convertToType(data['productCode'], 'String');
            }
            if (data.hasOwnProperty('site')) {
                obj['site'] = ApiClient.convertToType(data['site'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
        }
        return obj;
    }

    /**
    * The email address of the customer.
    * @member {String} customerEmail
    */
    'customerEmail' = undefined;
    /**
    * The product-code of the product the subscription is for.
    * @member {String} productCode
    */
    'productCode' = undefined;
    /**
    * The site URL that the subscription needs to be connectd to.
    * @member {String} site
    */
    'site' = undefined;
    /**
    * The first name of the customer.
    * @member {String} firstName
    */
    'firstName' = undefined;
    /**
    * The last name of the customers.
    * @member {String} lastName
    */
    'lastName' = undefined;




}
