/*
 * Yoast.com provisioning API
 * The Yoast provisioning API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateProvisionedSubscriptionDto model module.
 * @module model/CreateProvisionedSubscriptionDto
 * @version 1.0.0
 */
export class CreateProvisionedSubscriptionDto {
  /**
   * Constructs a new <code>CreateProvisionedSubscriptionDto</code>.
   * @alias module:model/CreateProvisionedSubscriptionDto
   * @class
   * @param customerEmail {String} The email address of the customer.
   * @param productCode {String} The product-code of the product the subscription is for.
   */
  constructor(customerEmail, productCode) {
    this.customerEmail = customerEmail;
    this.productCode = productCode;
  }

  /**
   * Constructs a <code>CreateProvisionedSubscriptionDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateProvisionedSubscriptionDto} obj Optional instance to populate.
   * @return {module:model/CreateProvisionedSubscriptionDto} The populated <code>CreateProvisionedSubscriptionDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateProvisionedSubscriptionDto();
      if (data.hasOwnProperty('customerEmail'))
        obj.customerEmail = ApiClient.convertToType(data['customerEmail'], 'String');
      if (data.hasOwnProperty('productCode'))
        obj.productCode = ApiClient.convertToType(data['productCode'], 'String');
      if (data.hasOwnProperty('site'))
        obj.site = ApiClient.convertToType(data['site'], 'String');
      if (data.hasOwnProperty('firstName'))
        obj.firstName = ApiClient.convertToType(data['firstName'], 'String');
      if (data.hasOwnProperty('lastName'))
        obj.lastName = ApiClient.convertToType(data['lastName'], 'String');
    }
    return obj;
  }
}

/**
 * The email address of the customer.
 * @member {String} customerEmail
 */
CreateProvisionedSubscriptionDto.prototype.customerEmail = undefined;

/**
 * The product-code of the product the subscription is for.
 * @member {String} productCode
 */
CreateProvisionedSubscriptionDto.prototype.productCode = undefined;

/**
 * The site URL that the subscription needs to be connected to.
 * @member {String} site
 */
CreateProvisionedSubscriptionDto.prototype.site = undefined;

/**
 * The first name of the customer.
 * @member {String} firstName
 */
CreateProvisionedSubscriptionDto.prototype.firstName = undefined;

/**
 * The last name of the customers.
 * @member {String} lastName
 */
CreateProvisionedSubscriptionDto.prototype.lastName = undefined;

