/*
 * Yoast.com provisioning API
 * The Yoast provisioning API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SetProvisionedSiteDto model module.
 * @module model/SetProvisionedSiteDto
 * @version 1.0.0
 */
export class SetProvisionedSiteDto {
  /**
   * Constructs a new <code>SetProvisionedSiteDto</code>.
   * @alias module:model/SetProvisionedSiteDto
   * @class
   * @param site {String} The site that should be connected to this subscription.
   */
  constructor(site) {
    this.site = site;
  }

  /**
   * Constructs a <code>SetProvisionedSiteDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SetProvisionedSiteDto} obj Optional instance to populate.
   * @return {module:model/SetProvisionedSiteDto} The populated <code>SetProvisionedSiteDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SetProvisionedSiteDto();
      if (data.hasOwnProperty('site'))
        obj.site = ApiClient.convertToType(data['site'], 'String');
    }
    return obj;
  }
}

/**
 * The site that should be connected to this subscription.
 * @member {String} site
 */
SetProvisionedSiteDto.prototype.site = undefined;

