/*
 * Yoast.com provisioning API
 * The Yoast provisioning API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {ScheduleDeleteUserDto} from '../model/ScheduleDeleteUserDto';
import {SubscriptionProvisioningResponseDto} from '../model/SubscriptionProvisioningResponseDto';

/**
* ProvisioningUsers service.
* @module api/ProvisioningUsersApi
* @version 1.0.0
*/
export class ProvisioningUsersApi {

    /**
    * Constructs a new ProvisioningUsersApi. 
    * @alias module:api/ProvisioningUsersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the apiProvisioningUserScheduleDeletePost operation.
     * @callback moduleapi/ProvisioningUsersApi~apiProvisioningUserScheduleDeletePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SubscriptionProvisioningResponseDto{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Schedule a delete for a subscription
     * Schedules a customer for gdpr delete.
     * @param {module:model/ScheduleDeleteUserDto} body 
     * @param {module:api/ProvisioningUsersApi~apiProvisioningUserScheduleDeletePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiProvisioningUserScheduleDeletePost(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling apiProvisioningUserScheduleDeletePost");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SubscriptionProvisioningResponseDto;

      return this.apiClient.callApi(
        '/api/provisioning/user/schedule-delete', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}