/*
 * Yoast.com provisioning API
 * The Yoast provisioning API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";

/**
* ProvisioningDownloads service.
* @module api/ProvisioningDownloadsApi
* @version 1.0.0
*/
export class ProvisioningDownloadsApi {

    /**
    * Constructs a new ProvisioningDownloadsApi. 
    * @alias module:api/ProvisioningDownloadsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the apiProvisioningDownloadsCurrentVersionGet operation.
     * @callback moduleapi/ProvisioningDownloadsApi~apiProvisioningDownloadsCurrentVersionGetCallback
     * @param {String} error Error message, if any.
     * @param {'String'{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve the current version for the productCode for the provisioner.
     * This route returns the latest version of the product that is offered to the customer when using the passed productCode.
     * @param {String} productCode The code used to create the product.
     * @param {module:api/ProvisioningDownloadsApi~apiProvisioningDownloadsCurrentVersionGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiProvisioningDownloadsCurrentVersionGet(productCode, callback) {
      
      let postBody = null;
      // verify the required parameter 'productCode' is set
      if (productCode === undefined || productCode === null) {
        throw new Error("Missing the required parameter 'productCode' when calling apiProvisioningDownloadsCurrentVersionGet");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'productCode': productCode
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = 'String';

      return this.apiClient.callApi(
        '/api/provisioning/downloads/currentVersion', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiProvisioningDownloadsCurrentZipGet operation.
     * @callback moduleapi/ProvisioningDownloadsApi~apiProvisioningDownloadsCurrentZipGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Redirect to the current zip for the productCode.
     * If a new version is available, you can use this route to redirect to the zip of that new version of the product.
     * @param {String} productCode The code used to create the product.
     * @param {module:api/ProvisioningDownloadsApi~apiProvisioningDownloadsCurrentZipGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiProvisioningDownloadsCurrentZipGet(productCode, callback) {
      
      let postBody = null;
      // verify the required parameter 'productCode' is set
      if (productCode === undefined || productCode === null) {
        throw new Error("Missing the required parameter 'productCode' when calling apiProvisioningDownloadsCurrentZipGet");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'productCode': productCode
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/provisioning/downloads/currentZip', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}