/**
 * Yoast.com provisioning API
 * The Yoast provisioning API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YoastProvisionerApiClient);
  }
}(this, function(expect, YoastProvisionerApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YoastProvisionerApiClient.ProvisioningDownloadsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProvisioningDownloadsApi', function() {
    describe('apiProvisioningDownloadsCurrentVersionGet', function() {
      it('should call apiProvisioningDownloadsCurrentVersionGet successfully', function(done) {
        //uncomment below and update the code to test apiProvisioningDownloadsCurrentVersionGet
        //instance.apiProvisioningDownloadsCurrentVersionGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiProvisioningDownloadsCurrentZipGet', function() {
      it('should call apiProvisioningDownloadsCurrentZipGet successfully', function(done) {
        //uncomment below and update the code to test apiProvisioningDownloadsCurrentZipGet
        //instance.apiProvisioningDownloadsCurrentZipGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
