/**
 * Yoast.com provisioning API
 * The Yoast provisioning API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SubscriptionApiJavascriptClient);
  }
}(this, function(expect, SubscriptionApiJavascriptClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SubscriptionApiJavascriptClient.SubscriptionProvisioningApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SubscriptionProvisioningApi', function() {
    describe('apiProvisioningSubscriptionsCreatePost', function() {
      it('should call apiProvisioningSubscriptionsCreatePost successfully', function(done) {
        //uncomment below and update the code to test apiProvisioningSubscriptionsCreatePost
        //instance.apiProvisioningSubscriptionsCreatePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiProvisioningSubscriptionsIdCancelPost', function() {
      it('should call apiProvisioningSubscriptionsIdCancelPost successfully', function(done) {
        //uncomment below and update the code to test apiProvisioningSubscriptionsIdCancelPost
        //instance.apiProvisioningSubscriptionsIdCancelPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiProvisioningSubscriptionsIdGet', function() {
      it('should call apiProvisioningSubscriptionsIdGet successfully', function(done) {
        //uncomment below and update the code to test apiProvisioningSubscriptionsIdGet
        //instance.apiProvisioningSubscriptionsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiProvisioningSubscriptionsIdRenewPost', function() {
      it('should call apiProvisioningSubscriptionsIdRenewPost successfully', function(done) {
        //uncomment below and update the code to test apiProvisioningSubscriptionsIdRenewPost
        //instance.apiProvisioningSubscriptionsIdRenewPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiProvisioningSubscriptionsIdSetSitePost', function() {
      it('should call apiProvisioningSubscriptionsIdSetSitePost successfully', function(done) {
        //uncomment below and update the code to test apiProvisioningSubscriptionsIdSetSitePost
        //instance.apiProvisioningSubscriptionsIdSetSitePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
