/*
 * Yoast.com provisioning API
 * The Yoast provisioning API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YoastProvisionerApiClient);
  }
}(this, function(expect, YoastProvisionerApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YoastProvisionerApiClient.SubscriptionProvisioningApi();
  });

  describe('(package)', function() {
    describe('SubscriptionProvisioningApi', function() {
      describe('apiProvisioningSubscriptionsCreatePost', function() {
        it('should call apiProvisioningSubscriptionsCreatePost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiProvisioningSubscriptionsCreatePost call and complete the assertions
          /*

          instance.apiProvisioningSubscriptionsCreatePost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YoastProvisionerApiClient.SubscriptionProvisioningResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiProvisioningSubscriptionsIdCancelPost', function() {
        it('should call apiProvisioningSubscriptionsIdCancelPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiProvisioningSubscriptionsIdCancelPost call and complete the assertions
          /*

          instance.apiProvisioningSubscriptionsIdCancelPost(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YoastProvisionerApiClient.SubscriptionProvisioningResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiProvisioningSubscriptionsIdGet', function() {
        it('should call apiProvisioningSubscriptionsIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiProvisioningSubscriptionsIdGet call and complete the assertions
          /*

          instance.apiProvisioningSubscriptionsIdGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YoastProvisionerApiClient.SubscriptionProvisioningResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiProvisioningSubscriptionsIdRefundPost', function() {
        it('should call apiProvisioningSubscriptionsIdRefundPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiProvisioningSubscriptionsIdRefundPost call and complete the assertions
          /*

          instance.apiProvisioningSubscriptionsIdRefundPost(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YoastProvisionerApiClient.SubscriptionProvisioningResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiProvisioningSubscriptionsIdRenewPost', function() {
        it('should call apiProvisioningSubscriptionsIdRenewPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiProvisioningSubscriptionsIdRenewPost call and complete the assertions
          /*

          instance.apiProvisioningSubscriptionsIdRenewPost(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YoastProvisionerApiClient.SubscriptionProvisioningResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiProvisioningSubscriptionsIdSetSitePost', function() {
        it('should call apiProvisioningSubscriptionsIdSetSitePost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiProvisioningSubscriptionsIdSetSitePost call and complete the assertions
          /*

          instance.apiProvisioningSubscriptionsIdSetSitePost(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YoastProvisionerApiClient.SubscriptionProvisioningResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
